platform :ios, '8.0'
use_frameworks!

target 'PengYQ', :exclusive => true do
    pod 'HanekeSwift', '0.10.0'
    pod 'Kingfisher', '1.8.0'
    pod 'SVProgressHUD', '1.1.3'
    pod 'UpRefreshControl','0.1.0'
    pod 'UpLoadMoreControl', '0.1.0'
    pod 'LvModelWindow', '0.1.0'
    pod 'DWTagList', '0.0.7'
    pod 'TTTAttributedLabel', '1.13.4'
    pod 'CTAssetsPickerController', '2.9.5'
    pod 'Toucan', '0.4.3'
    pod 'MHPrettyDate', '1.1.1'
end


post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end
