platform :ios, '8.0'
use_frameworks!

target 'PengYQ', :exclusive => true do
    pod 'AVOSCloud', '3.1.2.8'
    pod 'AVOSCloudIM', '3.1.2.8'
    pod 'HanekeSwift', '0.9.1'
    pod 'Kingfisher', '1.4.2'
    pod 'SVProgressHUD', '1.1.3'
    pod 'UpRefreshControl','0.1.0'
    pod 'UpLoadMoreControl', '0.1.0'
    pod 'LvModelWindow', '0.1.0'
    pod 'DWTagList', '0.0.7'
    pod 'TTTAttributedLabel', '1.13.4'
    pod 'CTAssetsPickerController', '2.9.5'
    pod 'Toucan', '0.2.0'
    pod 'MHPrettyDate', '1.1.1'
end